---
importFiles:
    # Paths must be relative to project root
    roles: []
    groups: []
    settings: []
    nodetypes:
        - src/Resources/node-types/Menu.json
        - src/Resources/node-types/MenuLink.json
