#!/bin/sh
set -e

#
# Override default entrypoint to add some maintenance and migration commands (PROD)
# DO NOT CALL THIS SCRIPT FOR WORKERS AND CRON containers (see docker-compose.yml)
#

# Print local env vars to .env.xxx.php file for performances and crontab jobs
/usr/local/bin/composer dump-env prod

# To improve performance (i.e. avoid decrypting secrets at runtime),
# you can decrypt your secrets during deployment to the "local" vault:
#APP_RUNTIME_ENV=prod /app/bin/console secrets:decrypt-to-local --force

if [ "${APP_ENV}" = "prod" ]; then
  /app/bin/console cache:warmup
fi

#
# Uncomment the following lines if you need to clear caches
# at each deployment (WILL slow down the deployment time)
#
# Clear caches after migrations
#/app/bin/console cache:clear -n
# Clear all cache pool on Symfony
#/app/bin/console cache:pool:clear cache.global_clearer -n

exec "$@"
