parameters:
    env(HTTP_CACHE_STALE_WHILE_REVALIDATE): 3600
    env(HTTP_CACHE_MAX_AGE): 60
    env(HTTP_CACHE_SHARED_MAX_AGE): 600

api_platform:
    patch_formats:
        json: ['application/merge-patch+json']
    enable_swagger_ui: false
    metadata_backward_compatibility_layer: false
    enable_re_doc: true
    graphql:
        graphiql:
            enabled: false
    show_webby: false
    swagger:
        versions: [3]
    title:       "%env(string:APP_TITLE)%"
    description: "%env(string:APP_DESCRIPTION)%"
    version:     '%env(string:APP_VERSION)%'
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity'
            - '%kernel.project_dir%/src/GeneratedEntity'
            - '%kernel.project_dir%/vendor/roadiz/core-bundle/src/Entity'
            - '%kernel.project_dir%/vendor/rezozero/tree-walker/src'
            - '%kernel.project_dir%/config/api_resources'
    defaults:
        pagination_client_items_per_page: true
        pagination_items_per_page: 15
        pagination_maximum_items_per_page: 50
        cache_headers:
            # Automatically generate etags for API responses.
            etag: true
            public: true
            # Default value for the response max age.
            max_age: '%env(int:HTTP_CACHE_MAX_AGE)%'
            # Default value for the response shared (proxy) max age.
            shared_max_age: '%env(int:HTTP_CACHE_SHARED_MAX_AGE)%'
            stale_while_revalidate: '%env(int:HTTP_CACHE_STALE_WHILE_REVALIDATE)%'
            # Default values of the "Vary" HTTP header.
            vary: ['Accept', 'Authorization', 'Origin', 'Accept-Encoding', 'Content-Type']
    collection:
        pagination:
            items_per_page_parameter_name: itemsPerPage

when@prod:
    api_platform:
        http_cache:
            invalidation:
                enabled: true
                varnish_urls: [ '%env(VARNISH_URL)%' ]
