framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis
        #app: cache.adapter.redis
        default_redis_provider: '%env(string:REDIS_DSN)%'

        # APCu (not recommended with heavy random-write workloads as memory fragmentation can cause perf issues)
        #app: cache.adapter.apcu
        pools:
            cache.contact_form_limiter: ~
            cache.custom_form_limiter: ~
            cache.newsletter_form_limiter: ~
            cache.password_protected_limiter: ~

when@prod:
    framework:
        cache:
            app: cache.adapter.redis

