# Read the documentation at https://github.com/thephpleague/flysystem-bundle/blob/master/docs/1-getting-started.md
flysystem:
    storages:
        documents_public.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/files'
        documents_private.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/files/private'
        intervention_request.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/files'
