nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT']
        allow_headers: ['Content-Type', 'Authorization', 'Www-Authenticate', 'x-g-recaptcha-response', 'Cache-Tags']
        expose_headers: ['Link', 'Www-Authenticate', 'Cache-Tags']
        max_age: 3600
    paths:
        '^/': ~
        '^/api/': ~
