when@prod:
    sentry:
        dsn: '%env(SENTRY_DSN)%'

        # If you are using Monolog, you also need this additional configuration to log the errors correctly:
        # https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration
        register_error_listener: false
        register_error_handler: false

        options:
            release: '%env(APP_VERSION)%'
            environment: '%env(SENTRY_ENVIRONMENT)%'
            ignore_exceptions:
                - 'Symfony\Component\ErrorHandler\Error\FatalError'
                - 'Symfony\Component\Debug\Exception\FatalErrorException'
                # Do not bloat Sentry with NotFoundHttpException
                - 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException'

    monolog:
        handlers:
            sentry:
                type: sentry
                level: !php/const Monolog\Logger::ERROR
                hub_id: Sentry\State\HubInterface
                fill_extra_context: true # Enables sending monolog context to Sentry
