name: ${APP_NAMESPACE}
services:
    db:
        hostname: db
        build:
            # Custom image for file permissions and performances
            target: mariadb
            args:
                UID: ${UID}
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        networks:
            - default
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
            MARIADB_DATABASE: ${MARIADB_DATABASE:-roadiz}
            MARIADB_USER: ${MARIADB_USER:-roadiz}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD:-roadiz}

    pma:
        image: phpmyadmin:5.2.1
        environment:
            PMA_HOST: db
            UPLOAD_LIMIT: 64M
            PMA_USER: ${MARIADB_USER:-roadiz}
            PMA_PASSWORD: ${MARIADB_PASSWORD:-roadiz}
        depends_on:
            - db
        networks:
            - frontproxynet
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${APP_NAMESPACE}_pma.loadbalancer.server.scheme=http"
            - "traefik.http.services.${APP_NAMESPACE}_pma.loadbalancer.server.port=80"
            - "traefik.http.services.${APP_NAMESPACE}_pma.loadbalancer.passhostheader=true"
            - "traefik.http.routers.${APP_NAMESPACE}_pma.entrypoints=http,https"
            - "traefik.http.routers.${APP_NAMESPACE}_pma.entrypoints=https"
            - "traefik.http.routers.${APP_NAMESPACE}_pma.tls=true"
            - "traefik.http.routers.${APP_NAMESPACE}_pma.rule=HostRegexp(${HOSTNAME_PMA})"
            - "traefik.http.routers.${APP_NAMESPACE}_pma.service=${APP_NAMESPACE}_pma"

    app: &app_template
        # Nginx does not resolve `app` hostname correctly
        hostname: app
        # Need to pass all vars to docker env for Crontab and supervisor scripts
        #env_file: "./.env.local"
        build:
            target: php-dev
            args:
                UID: ${UID}
        depends_on:
            - db
            - solr
            - redis
        volumes:
            - ./:/app
        networks:
            default:
        environment:
            TRUSTED_PROXIES: ${TRUSTED_PROXIES}
            UID: ${UID}
            DEFAULT_GATEWAY: ${DEFAULT_GATEWAY}

    nginx:
        build:
            target: nginx-dev
            args:
                UID: ${UID}
        depends_on:
            - app
        volumes:
            - ./:/app
        networks:
            default:
#            frontproxynet:
#                aliases:
#                    - ${APP_NAMESPACE}_nginx
#        labels:
#            - "traefik.enable=true"
#            - "traefik.http.services.${APP_NAMESPACE}.loadbalancer.server.scheme=http"
#            - "traefik.http.services.${APP_NAMESPACE}.loadbalancer.server.port=80"
#            - "traefik.http.services.${APP_NAMESPACE}.loadbalancer.passhostheader=true"
#            # Enable healthcheck to prevent routing traffic to not-ready service
#            #- "traefik.http.services.${APP_NAMESPACE}.loadbalancer.healthcheck.path=/health-check"
#            #- "traefik.http.services.${APP_NAMESPACE}.loadbalancer.healthcheck.interval=10s"
#            #- "traefik.http.services.${APP_NAMESPACE}.loadbalancer.healthcheck.timeout=3s"
#            #- "traefik.http.services.${APP_NAMESPACE}.loadbalancer.healthcheck.headers.x-health-check=${APP_HEALTH_CHECK_TOKEN}"
#            - "traefik.http.routers.${APP_NAMESPACE}.entrypoints=http,https"
#            - "traefik.http.routers.${APP_NAMESPACE}.entrypoints=https"
#            - "traefik.http.routers.${APP_NAMESPACE}.tls=true"
#            # Combine Host and PathRegexp to allow API and Frontend to share same domain name
#            - "traefik.http.routers.${APP_NAMESPACE}.rule=HostRegexp(${HOSTNAME}) && PathRegexp(${PATH_PREFIX})"
#            - "traefik.http.routers.${APP_NAMESPACE}.service=${APP_NAMESPACE}"

    worker:
        <<: *app_template
        hostname: worker
        deploy:
            # Do not use more than 1 replica if you're using Varnish and need to purge/ban cache
            # from your workers. Varnish ACL hostnames won't be resolved correctly.
            replicas: 1
        # official php-fpm image uses SIGQUIT
        stop_signal: SIGTERM
        entrypoint: [ "php", "/app/bin/console", "messenger:consume", "async", "--time-limit=600" ]
        restart: unless-stopped

    cron:
        <<: *app_template
        hostname: cron
        # official php-fpm image uses SIGQUIT
        stop_signal: SIGTERM
        entrypoint: 'docker-cron-entrypoint'
        restart: unless-stopped
        user: root

    solr:
        build:
            # Custom image for file permissions
            target: solr
            args:
                UID: ${UID}
        volumes:
            - "solr:/var/solr"
        command:
            - solr-precreate
            - ${SOLR_CORE_NAME}
        networks:
            frontproxynet:
                aliases:
                    - ${APP_NAMESPACE}_solr
            default:
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${APP_NAMESPACE}_solr.loadbalancer.server.scheme=http"
            - "traefik.http.services.${APP_NAMESPACE}_solr.loadbalancer.server.port=8983"
            - "traefik.http.services.${APP_NAMESPACE}_solr.loadbalancer.passhostheader=true"
            - "traefik.http.routers.${APP_NAMESPACE}_solr.entrypoints=http,https"
            - "traefik.http.routers.${APP_NAMESPACE}_solr.rule=HostRegexp(${HOSTNAME_SOLR})"
            - "traefik.http.routers.${APP_NAMESPACE}_solr.service=${APP_NAMESPACE}_solr"
            - "traefik.http.routers.${APP_NAMESPACE}_solr.tls=true"

    mailer:
        hostname: mailer
        image: axllent/mailpit
        networks:
            - frontproxynet
            - default
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${APP_NAMESPACE}_mailer.loadbalancer.server.scheme=http"
            - "traefik.http.services.${APP_NAMESPACE}_mailer.loadbalancer.server.port=8025"
            - "traefik.http.services.${APP_NAMESPACE}_mailer.loadbalancer.passhostheader=true"
            - "traefik.http.routers.${APP_NAMESPACE}_mailer.entrypoints=http,https"
            - "traefik.http.routers.${APP_NAMESPACE}_mailer.rule=HostRegexp(${HOSTNAME_MAILER})"
            - "traefik.http.routers.${APP_NAMESPACE}_mailer.service=${APP_NAMESPACE}_mailer"
            - "traefik.http.routers.${APP_NAMESPACE}_mailer.entrypoints=https"
            - "traefik.http.routers.${APP_NAMESPACE}_mailer.tls=true"

    # Use Redis for Cache, Messaging and Sessions
    redis:
        hostname: redis
        image: redis:7-alpine
        volumes:
            - redis:/data
        networks:
            - default

    redis-commander:
        image: ghcr.io/joeferner/redis-commander:0.9.0
        environment:
            REDIS_HOST: redis
        depends_on:
            - redis

    varnish:
        build:
            target: varnish
        # https://github.com/varnish/docker-varnish/issues/53
        user: root
        # Prevent cache-tags to overflow headers max size by doubling default values
        # https://github.com/api-platform/core/issues/3168
        # https://www.varnish-software.com/developers/tutorials/troubleshooting-varnish/
        command: "-p http_resp_hdr_len=16384 -p http_resp_size=65536"
        tmpfs: /var/lib/varnish/varnishd:exec
        depends_on:
            - nginx
        links:
            - nginx:nginx
            - app:app
            - cron:cron
            - worker:worker
        networks:
            - frontproxynet
            - default
        environment:
            VARNISH_SIZE: ${VARNISH_SIZE}
        labels:
            - "traefik.enable=true"
            - "traefik.http.services.${APP_NAMESPACE}_varnish.loadbalancer.server.scheme=http"
            - "traefik.http.services.${APP_NAMESPACE}_varnish.loadbalancer.server.port=80"
            - "traefik.http.services.${APP_NAMESPACE}_varnish.loadbalancer.passhostheader=true"
            # Enable healthcheck to prevent routing traffic to not-ready service
            #- "traefik.http.services.${APP_NAMESPACE}_varnish.loadbalancer.healthcheck.path=/health-check"
            #- "traefik.http.services.${APP_NAMESPACE}_varnish.loadbalancer.healthcheck.interval=10s"
            #- "traefik.http.services.${APP_NAMESPACE}_varnish.loadbalancer.healthcheck.timeout=3s"
            #- "traefik.http.services.${APP_NAMESPACE}_varnish.loadbalancer.healthcheck.headers.x-health-check=${APP_HEALTH_CHECK_TOKEN}"
            - "traefik.http.routers.${APP_NAMESPACE}_varnish.entrypoints=http,https"
            - "traefik.http.routers.${APP_NAMESPACE}_varnish.rule=HostRegexp(${HOSTNAME_VARNISH}) && PathRegexp(${PATH_PREFIX})"
            - "traefik.http.routers.${APP_NAMESPACE}_varnish.service=${APP_NAMESPACE}_varnish"
            - "traefik.http.routers.${APP_NAMESPACE}_varnish.tls=true"

networks:
    frontproxynet:
        external: true
    # If you need to use port forwarding, fixing default gateway can be useful
    # to keep same host IP address between service restarts
    default:
        ipam:
            driver: default
            config:
                -   subnet: ${DEFAULT_GATEWAY}/24

volumes:
    redis:
    solr:
