name: ${APP_NAMESPACE}
services:
    db:
        hostname: db
        build:
            # Custom image for file permissions and performances
            target: mariadb
            args:
                UID: ${UID}
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        networks:
            - default
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
            MARIADB_DATABASE: ${MARIADB_DATABASE:-roadiz}
            MARIADB_USER: ${MARIADB_USER:-roadiz}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD:-roadiz}

    pma:
        image: phpmyadmin:5.2.1
        environment:
            PMA_HOST: db
            UPLOAD_LIMIT: 64M
            PMA_USER: ${MARIADB_USER:-roadiz}
            PMA_PASSWORD: ${MARIADB_PASSWORD:-roadiz}
        depends_on:
            - db

    app: &app_template
        # Nginx does not resolve `app` hostname correctly
        hostname: app
        build:
            target: php-dev
            args:
                UID: ${UID}
        depends_on:
            - db
            - redis
        volumes:
            - ./:/app
        networks:
            default:
        environment:
            TRUSTED_PROXIES: ${TRUSTED_PROXIES}
            UID: ${UID}
            DEFAULT_GATEWAY: ${DEFAULT_GATEWAY}

    nginx:
        build:
            target: nginx-dev
            args:
                UID: ${UID}
        depends_on:
            - app
        volumes:
            - ./:/app

    worker:
        <<: *app_template
        hostname: worker
        # official php-fpm image uses SIGQUIT
        stop_signal: SIGTERM
        entrypoint: [ "php", "-d", "memory_limit=-1", "/app/bin/console", "messenger:consume", "async", "--time-limit=600" ]
        restart: unless-stopped

    scheduler:
        <<: *app_template
        hostname: scheduler
        # official php-fpm image uses SIGQUIT
        stop_signal: SIGTERM
        entrypoint: [ "php", "-d", "memory_limit=-1", "/app/bin/console", "messenger:consume", "scheduler_default", "--time-limit=600" ]
        restart: unless-stopped

    mailer:
        hostname: mailer
        image: axllent/mailpit

    # Use Redis for Cache, Messaging and Sessions
    redis:
        hostname: redis
        image: redis:7-alpine
        volumes:
            - redis:/data

    redis-commander:
        image: ghcr.io/joeferner/redis-commander:0.9.0
        environment:
            REDIS_HOST: redis
        depends_on:
            - redis

    varnish:
        build:
            target: varnish
        # https://github.com/varnish/docker-varnish/issues/53
        user: root
        # Prevent cache-tags to overflow headers max size by doubling default values
        # https://github.com/api-platform/core/issues/3168
        # https://www.varnish-software.com/developers/tutorials/troubleshooting-varnish/
        command: "-p http_resp_hdr_len=16384 -p http_resp_size=65536"
        tmpfs: /var/lib/varnish/varnishd:exec
        depends_on:
            - nginx
        links:
            - nginx:nginx
        environment:
            VARNISH_SIZE: ${VARNISH_SIZE}

networks:
    # If you need to use port forwarding, fixing default gateway can be useful
    # to keep same host IP address between service restarts
    default:
        ipam:
            driver: default
            config:
                -   subnet: ${DEFAULT_GATEWAY}/24

volumes:
    redis:
