#
# Only use this docker compose template if you prefer using symfony server:start
#
name: skeleton
services:
    db:
        build:
            # Custom image for file permissions
            context: ./docker/mysql
            args:
                USER_UID: ${USER_UID}
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        ports:
            - ${PUBLIC_DB_PORT}:3306/tcp
        networks:
            default:
        volumes:
            - "db_data:/var/lib/mysql:delegated"
            - "./docker/mysql/performances.cnf:/etc/mysql/conf.d/performances.cnf"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

#    solr:
#        build:
#            # Custom image for file permissions
#            context: ./docker/solr
#            args:
#                USER_UID: ${USER_UID}
#        ports:
#            - "${PUBLIC_SOLR_PORT}:8983/tcp"
#        volumes:
#            - "solr_data:/var/solr:delegated"
#        environment:
#            SOLR_UID: ${USER_UID}
#            SOLR_GID: ${USER_UID}
#        command:
#            - solr-precreate
#            - ${SOLR_CORE_NAME}

    mailer:
        image: mailhog/mailhog
        ports:
            - ${PUBLIC_MAILER_PORT}:8025/tcp
            - ${PUBLIC_SMTP_PORT}:1025/tcp

    # Use Redis for Cache, Messaging and Sessions
    redis:
        image: redis:7-alpine
        ports:
            - ${PUBLIC_REDIS_PORT}:6379/tcp

# using named volumes for performance’s sake
volumes:
    db_data:
    solr_data:
