#!/bin/sh
set -e

# Print env infos
echo "APP_ENV=${APP_ENV}";
echo "APP_RUNTIME_ENV=${APP_RUNTIME_ENV}";
echo "APP_DEBUG=${APP_DEBUG}";

#
# Override default entrypoint to add some maintenance and migration commands (PROD)
# DO NOT CALL THIS SCRIPT FOR WORKERS AND CRON containers (see docker-compose.yml)
#

# Print local env vars to .env.xxx.php file for performances and crontab jobs
/usr/local/bin/composer dump-env prod
/app/bin/console assets:install -n

# To improve performance (i.e. avoid decrypting secrets at runtime),
# you can decrypt your secrets during deployment to the "local" vault:
#APP_RUNTIME_ENV=prod /app/bin/console secrets:decrypt-to-local --force

# Clear caches after migrations
/app/bin/console cache:clear -n
# Clear all cache pool on Symfony
/app/bin/console cache:pool:clear cache.global_clearer -n

/app/bin/console lexik:jwt:generate-keypair --skip-if-exists

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- frankenphp run "$@"
fi

exec "$@"
