sentry:
    register_error_listener: false

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        nested:
            type: stream
            path: php://stderr
            level: debug
            formatter: monolog.formatter.json
#        sentry:
#            type: sentry
#            level: !php/const Monolog\Logger::ERROR
#            hub_id: Sentry\State\HubInterface
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        custom:
            type: service
            id: RZ\Roadiz\CoreBundle\Logger\DoctrineHandler
            level: info
            channels: [ "app" ]
