resources:
    App\GeneratedEntity\NSMenuLink:
        shortName: MenuLink
        types:
            - MenuLink
        operations:
            menulink_get:
                method: GET
                class: ApiPlatform\Metadata\Get
                shortName: MenuLink
                normalizationContext:
                    groups:
                        - nodes_sources
                        - node_listing
                        - urls
                        - tag_base
                        - translation_base
                        - document_display
                        - document_thumbnails
                        - document_display_sources
