resources:
    App\GeneratedEntity\NSMenu:
        shortName: Menu
        types:
            - Menu
        operations:
            menu_get:
                method: GET
                class: ApiPlatform\Metadata\Get
                shortName: Menu
                normalizationContext:
                    groups:
                        - nodes_sources
                        - node_listing
                        - urls
                        - tag_base
                        - translation_base
                        - document_display
                        - document_thumbnails
                        - document_display_sources
