#index:
#    path: /
#    controller: App\Controller\DefaultController::index

roadiz_core:
    resource: "@RoadizCoreBundle/config/routing.yaml"

roadiz_rozier:
    resource: "@RoadizRozierBundle/config/routing.yaml"

rz_intervention_request:
    resource: "@RZInterventionRequestBundle/Resources/config/routing.yml"
    prefix: /

api_login_check:
    methods: [POST]
    path: /api/token

api_contact_form_definition:
    methods: [GET]
    path: /api/contact_form/definition
    defaults:
        _controller: App\Controller\ContactFormController::definitionAction
        _locale: en
        _format: json

api_contact_form_post:
    methods: [POST]
    path: /api/contact_form/post
    defaults:
        _controller: App\Controller\ContactFormController::formAction
        _locale: en
        _format: json
